replicaCount: 2

config:
  APP_ENV: qa

ingress:
  enabled: true
  className: nginx
  
  hosts:
    - host: qa.example.com
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 200m
    memory: 256Mi

secret:
  dbPassword: "qa-password-456"